### ISSUE TITLE
It is not clear how the "libraryVersion" field in config file is used

### ISSUE THREAD

**Issue by AndreaBartolini** [OpenModelica/OpenModelicaLibraryTesting#124]
I'm using the `OpenModelicaLibraryTesting` on a Windows machine to test my libraries in local. If I don't use the field `"libraryVersion":"xxx",` in the `config` file the test is done correctly but if I add said record not any test is done.

The library has name `MyLib` and is saved in multiple files, so `MyLib` is the name of the dir which contains the file `package.mo`. 
The `MyLib` dir is placed in a dir like `c:\MyLibDir\master` so the complete path to the library is `c:\MyLibDir\master\MyLib`.

The command used to run the `OpenModelicaLibraryTesting` is the following:
`python test.py --noClean --execAllTests --jobs=1 --noSync --timeout=300 --branch="master" --libraries="c:/MyLibDir/master" --output="C:/MyOutputDir" c:/MyConfigFile`

The test works with the following `MyConfigFile`:
```
[
  {
    "library":"MyLib",
    "referenceFiles":"C:/MyRefFiles/MyLib"
  }
]
```

It doesn't work with the following `MyConfigFile`:
```
[
  {
    "library":"MyLib",
    "libraryVersion":"1",
    "referenceFiles":"C:/MyRefFiles/MyLib"
  }
]
```
It seems that the script, in this case, attaches `_1` to the library name so I tried to change the library dir in `MyLib_1` but also in this case the script doesn't work.

In the `MyLib` library there is the `annotation(version="1")` 

Where am I going wrong?

**Comment by AndreaBartolini** [comment]
keeping @casella in the loop

**Comment by AndreaBartolini** [comment]
Looking at the OpenModelica scripting documentation I found that the name of the library dir (or the library package) expected by the `loadModel(lib,{"ver"})` is `lib ver`, (so not lib_ver).

Following the rule the script works. 

In my opinion is not so good to repeat the same information (the library version) in the library annotation and in the library package (or directory) name. But is just a my opinion....

**Comment by casella** [comment]
@AndreaBartolini, the `lib ver` directory name is specified by the MLS, [Section 18.8.3](https://specification.modelica.org/maint/3.6/annotations.html#mapping-of-versions-to-file-system). It is necessary if we want to store multiple versions of the same library under the same MODELICAPATH.
