### ISSUE TITLE
Provide a HowTo for setting up your own testing infrastructure

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelicaLibraryTesting#13]
Many OMC users may benefit from using a test infrastructure like the one we run on Jenkins, producing html test reports on new nightly builds and/or on new commits to libraries, but they'd like to do it on their own models that the can't/won't make public or share with the OSMC.

We should write a short guide on how to do that. @sjoelund provided a first sketch [here](https://github.com/OpenModelica/OpenModelicaLibraryTesting#readme), I guess we could make it a bit more informative also for non-experts.

@AnHeuermann, would you like to give it a try? @AndreaBartolini could act as beta-tester, trying to set up the thing on his machine based on your instructions.

Thanks!

**Comment by AnHeuermann** [comment]
Sure, I can try to set it up on one of our servers and edit the README while I'm on it.
Could be useful for @kabdelhak to test the new backend at some point.

**Comment by casella** [comment]
Two birds with one stone! 😄
