### ISSUE TITLE
Incorrect output interval set in FMPy simulations

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelicaLibraryTesting#162]
If you check the [Buildings_11/master](https://libraries.openmodelica.org/branches/master/Buildings_11/Buildings_11.html) test report, most simulations take a few seconds and only a minority may take a few tens of seconds, with very few cases in the minutes range.

When testing FMI-based simulation, performed by running OMC-generated FMUs in OMSimulator, the [Buildings_11/master-fmi](https://libraries.openmodelica.org/branches/master-fmi/Buildings_11/Buildings_11.html) report shows a significant number of cases timing out without results, but the other cases are simulated successfully within reasonable amounts of time. They are typically 2-4 times slower than with the regular runtime, but they work fine otherwise.

When testing FMI-based simulation with FMPy, [Buildings_11/master-fmi-fmpy](https://libraries.openmodelica.org/branches/master-fmi-fmpy/Buildings_11/Buildings_11.html), about 30% of simulations behave in this way:
- the simulation runs for 400 s
- the test program kills it for timeout violation well before StopTime is reached. This is still reported as successful simulation, which is questionable
- the result computed so far are often correct and pass verification, or they have tiny numerical issues.

So, it seems that the simulations are producing the correct results, at least most of the times, but with a really horribly slow performance.

For example, take the `Buildings.Air.Systems.SingleZone.VAV.BaseClasses.Validation.ControllerHeatingFan` model of the Buildings 11.0.0. 
- With the [regular runtime](https://libraries.openmodelica.org/branches/master/Buildings_11/Buildings_11.html), the simulation takes 0.02 s. 
- With the [fmi-omsimulator toolchain](https://libraries.openmodelica.org/branches/master-fmi/Buildings_11/Buildings_11.html) it takes 0.12 s. The verification fails with 1/6 signals, but it seems due to bad sampling or something, nothing serious.
- With the [fmi-fmpy toolchain](https://libraries.openmodelica.org/branches/master-fmi-fmpy/Buildings_11/Buildings_11.html) it times out after 400 s, though the verification is passing

The specific model in question is a very simple one (just a couple PI controllers) so there is no reason it shouldn't work. What this model has in common with other models failing this way is that it has
```
annotation(experiment(StopTime=604800,  Tolerance=1e-06)
```
so it lacks an Interval annotation. My understanding is that in this case the FMPy simulation is using some stupid very small default communication interval, e.g. 0.002, so it is computing 300,000,000 time steps, which of course takes forever.

I thought this issue was settled in OpenModelica/OpenModelica#11859 and OpenModelica/OpenModelica#12070, but apparently there is still something wrong there 🙄 

Besides, following the discussion in modelica/fmi-standard#1980, the decision was that, as far as FMI 2.0.5, the `stepSize` attribute has no meaning in FMI-ME, so the solution we implemented to pass the communication interval via that attribute in the xml file is questionable. It's too bad such information is not provided by the XML file according to the standard, I opened modelica/fmi-standard#1991 to discuss it, but we have to live without it for the time being.

I would propose a robust solution that avoids this kind of issues at the root. 
- When generating the FMU, fetch the experiment annotation of the Modelica model.
- If `Interval` is defined, we just pass it as argument to the fmpy `--output-interval` flag

https://github.com/OpenModelica/OpenModelicaLibraryTesting/blob/e8d92cd4f00ba3dc4bbf17ac543f3e24d6efce42/testmodel.py#L500-L503

- If it isn't, we pass the default interval set in the CI, which can be computed as (`StopTime - StartTime)/min(2500, 2*number_time_steps_reference)`, if I am not mistaken. Or something like that. Something consistent with the plain Modelica testing, for God's sake 😃

**Comment by adrpo** [comment]
To be fixed by PR #163 which updates FMPy to the latest automatically, the old FMPy could not properly handle `--output-interval` with decimals!?!

**Comment by casella** [comment]
Indeed, and it is us who found out, see: CATIA-Systems/FMPy#655.
