### ISSUE TITLE
The gbode job apparently doesn't generate regression reports

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelicaLibraryTesting#180]
@adrpo, we ran a gbode job recently but it doesn't show up in https://libraries.openmodelica.org/branches/history/. Any idea?

Thanks!

**Comment by phannebohm** [comment]
I think it works now. See https://libraries.openmodelica.org/branches/history/gbode/

Can we have that running weekly?

**Comment by adrpo** [comment]
I added it to job:
https://test.openmodelica.org/jenkins/job/LibraryTesting/job/Weekly%20Ripper%202/
