### ISSUE TITLE
Progress output during test run

### ISSUE THREAD

**Issue by bilderbuchi** [OpenModelica/OpenModelicaLibraryTesting#41]
It would be convenient if, during running the individual tests in parallel, one would get some progress indication. Currently, there's no output produced on the console even during long simulations until the "Execution time" is reported.

The `joblib.Parallel` class has a [`verbose` argument](https://joblib.readthedocs.io/en/latest/parallel.html#parallel-reference-documentation) that should enable that easily, so it would probably be sufficient if at https://github.com/OpenModelica/OpenModelicaLibraryTesting/blob/680d9f69aa2e9a12d3ec9a2ef677cc2370bd4540/test.py#L684 the invocation would be `Parallel(n_jobs=n_jobs, verbose=51)(...` (51 to be output to stdout, not stderr).

I'm wondering if that could also report the model/test name (that would be most useful).

**Comment by casella** [comment]
@bilderbuchi could you make a PR?

Then maybe @AnHeuermann could pull it and test it on his local library testing environment.

**Comment by bilderbuchi** [comment]
As I mentioned on our recent call, I still need to sort out how to get the release to sign the CLA. Until then I'll have to avoid code contributions.

**Comment by casella** [comment]
In any case, I think it's best to wait until we branch off maintenance/v1.22, this thing could potentially cause low-level issues, so we need a long enough testing period in the nightly builds first.
