### ISSUE TITLE
ExternalMedia fails models with partial and experiment annotation

### ISSUE THREAD

**Issue by bilderbuchi** [OpenModelica/OpenModelicaLibraryTesting#44]
`ExternalMedia.Test.GenericModels.TestBasePropertiesDynamic` and `ExternalMedia.Test.GenericModels.TestRunner` are both `partial` models that have an `experiment` annotation. This trips up testing.

Both are underdetermined, so the `partial` is justified. 
The experiment annotation is probably there to be DRY when extending from these models.

It seems the best course of action is to extend the `ignoreModelPrefix` https://github.com/OpenModelica/OpenModelicaLibraryTesting/blob/5a71cc63211d9363eefea6a8cd816739af540d2f/configs/conf.json#L209C5-L209C55 to ignore those two models.

**Comment by casella** [comment]
@bilderbuchi, experiment annotations are actually not inherited, so there is really no point in having those two annotations. I invited you to contribute to the library, so you can fix that yourself. Thanks!

**Comment by bilderbuchi** [comment]
Ah, I didn't know that! In that case, can you transfer this issue to the ExternalMedia repository, please?
