### ISSUE TITLE
devscripts deprecation warning

### ISSUE THREAD

**Issue by AnHeuermann** [OpenModelica/OpenModelicaLibraryTesting#65]
When installing [requirements.txt](https://github.com/OpenModelica/OpenModelicaLibraryTesting/blob/master/requirements.txt) with pip the following warning is displayed:

```bash
$ pip install -r requirements.txt
DEPRECATION: devscripts 2.22.1ubuntu1 has a non-standard version number. pip 24.1 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of devscripts or contact the author to suggest that they release a version with a conforming version number. Discussion can be found at https://github.com/pypa/pip/issues/12063
```

Replace, remove or update [devscripts](ttps://github.com/tbobm/devscripts).

**Comment by bilderbuchi** [comment]
Doing 
```
pip install -r https://raw.githubusercontent.com/OpenModelica/OpenModelicaLibraryTesting/master/requirements.txt
```
in a fresh environment, I cannot reproduce, installation completes without that package even mentioned. 
Where does that come from? A Docker container maybe?

**Comment by AnHeuermann** [comment]
I re-created a clean Python virtual environment and now I can't reproduce it. Maybe it was some other package leftover on my system.
